version: "3"
services:
  golang:
    container_name: golang
    image: jinostroza/golang:1.0.2
    build: ./golang
    working_dir: /work
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    volumes:
    - ./golang/src/:/work
    ports:
      - 5001:5000

